// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMCNLhwFvlgSxE5Y503Zk-_jvq5_XETM',
    appId: '1:277416170289:web:732ebe068f2797ade89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    authDomain: 'hospital-management-c7ddc.firebaseapp.com',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
    measurementId: 'G-CTK081R1XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByO5gcV-BrDjE7-uC4kcfAnp3JTzuYS14',
    appId: '1:277416170289:android:7394ae168a7a94fae89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGEc1bmqhPdM5ROUrHSOCDiDA4S8dNkIg',
    appId: '1:277416170289:ios:5fd4a88546a6bbe2e89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
    iosClientId: '277416170289-febbkghtrffjftmcnniiivoho1f94lp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.medease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGEc1bmqhPdM5ROUrHSOCDiDA4S8dNkIg',
    appId: '1:277416170289:ios:5fd4a88546a6bbe2e89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
    iosClientId: '277416170289-febbkghtrffjftmcnniiivoho1f94lp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.medease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsMCNLhwFvlgSxE5Y503Zk-_jvq5_XETM',
    appId: '1:277416170289:web:732ebe068f2797ade89610',
    messagingSenderId: '277416170289',
    projectId: 'hospital-management-c7ddc',
    authDomain: 'hospital-management-c7ddc.firebaseapp.com',
    storageBucket: 'hospital-management-c7ddc.firebasestorage.app',
    measurementId: 'G-CTK081R1XJ',
  );
}
